<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Biaya_mahasiswa_model extends CI_Model
{

    public $table = 'biaya_mahasiswa';
    public $id = 'id_biaya';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('a.id_biaya,a.jenis_biaya,a.acc,a.nama_biaya,a.jumlah_biaya,a.set_biaya,a.status_biaya,a.id_user_set,a.id_user_status,a.deleted,a.id_smt,a.id_sms,b.nm_lemb,c.nm_jns_daftar');
        $this->datatables->from('biaya_mahasiswa a');
        //add this line for join
        $this->datatables->join('pddikti_tr_sms b', 'a.id_sms = b.id_sms');
        $this->datatables->join('pddikti_re_jenis_pendaftaran c', 'a.jenis_biaya = c.id_jns_daftar');
        $this->datatables->add_column('action', anchor(site_url('biaya_mahasiswa/update/$1'),'<button type="button" class="btn btn-info">Update</button>'), 'id_biaya');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        $this->db->join('pddikti_tr_sms a','a.id_sms=b.id_sms');
        $this->db->join('pddikti_re_jenis_pendaftaran c','b.jenis_biaya=c.id_jns_daftar');
        return $this->db->get('biaya_mahasiswa b')->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_biaya', $q);
	$this->db->or_like('jenis_biaya', $q);
	$this->db->or_like('acc', $q);
	$this->db->or_like('nama_biaya', $q);
	$this->db->or_like('jumlah_biaya', $q);
	$this->db->or_like('set_biaya', $q);
	$this->db->or_like('status_biaya', $q);
	$this->db->or_like('id_user_set', $q);
	$this->db->or_like('id_user_status', $q);
	$this->db->or_like('deleted', $q);
	$this->db->or_like('id_smt', $q);
	$this->db->or_like('id_sms', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_biaya', $q);
	$this->db->or_like('jenis_biaya', $q);
	$this->db->or_like('acc', $q);
	$this->db->or_like('nama_biaya', $q);
	$this->db->or_like('jumlah_biaya', $q);
	$this->db->or_like('set_biaya', $q);
	$this->db->or_like('status_biaya', $q);
	$this->db->or_like('id_user_set', $q);
	$this->db->or_like('id_user_status', $q);
	$this->db->or_like('deleted', $q);
	$this->db->or_like('id_smt', $q);
	$this->db->or_like('id_sms', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }
function get_sms() {
        $query = $this->db->get('pddikti_tr_sms');
        return $query->result();
    }
     function get_jd() {
        $query = $this->db->get('pddikti_re_jenis_pendaftaran');
        return $query->result();
    }
    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Biaya_mahasiswa_model.php */
/* Location: ./application/models/Biaya_mahasiswa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-03-31 08:19:53 */
/* http://harviacode.com */